name: PetBuddy
on: 
  push:
    branches:
      - master
      - petbuddy/version-1

jobs: 
  PetBuddy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Set up Ruby and Bundler
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full
        gem install bundler
    - name: Install pod dependency
      run: |
        cd ios
        bundle install
        bundle exec pod install
    - name: Run tests
      run: npm test